package br.com.vinicius.util.enums;

public enum NomeCampoEnum {
	CODIGO_PESSOA
	, NOME_PESSOA
	, CPF
	, RG
	, DATA_NASCIMENTO
	, CODIGO_ENDERECO
	, LOGRADOURO
	, COMPLEMENTO
	, NUMERO
	, CODIGO_BAIRRO
	, NOME_BAIRRO
	, CODIGO_CIDADE
	, NOME_CIDADE
	, CODIGO_ESTADO
	, NOME_ESTADO
	, SIGLA_ESTADO
	, CODIGO_VEIC
	, MODELO_VEIC
	, ANO_FABRICACAO_VEIC
	, ANO_MODELO_VEIC
	, COR_VEIC
	, CODIGO_MARCA_VEIC
	, NOME_MARCA_VEIC

}
